Universe = vanilla
Executable = condor_scripts/ansatz_expressive_test.sh
Arguments = 3 6 1 True
environment = "HOME=/srv01/technion/dorsh"

# Specify file transfer settings - the setting should ALWAYS be no!!!!
should_transfer_files = NO



Output =  /storage/ph_lindner/dorsh/RFCI/output/vqe_Nx-3_Ny-6_layer-1_flux-True_output.log
Error =  /storage/ph_lindner/dorsh/RFCI/output/vqe_Nx-3_Ny-6_layer-1_flux-True_error.log
Log =  /storage/ph_lindner/dorsh/RFCI/output/vqe_Nx-3_Ny-6_layer-1_flux-True_condor.log
Initialdir = /storage/ph_lindner/dorsh/RFCI
Request_Cpus = 1
# if you don't define value for memory the default is 2gb it is advisable to specify a value
Request_Memory = 35GB
Queue