simulation_type: jax

data:
  name: RFCI
  Nx: 2
  Ny: 6
  n: 
  id:
  p: -1
  q: 3 

resarach_question: 'test integreation'

config0:
  band_energy: 1
  interaction_strength: 0.1
  ground_state_degeneracy: 3
  overlap_optimization: True
  maxiter: 10000000
  layer_numer: 4
  random_initial_parametrs: False
  loss: 
  # optimizer: 'my_optimizer'
  # optimizer: 'my_optimizer_V2'
  # optimizer: 'SPSA'
  # optimizer: 'SLSQP'
  # optimizer: 'cobyla'
  optimizer: 'BFGS'
  cktp_iters: 
