simulation_type: jax

data:
  name: RFCI
  Nx: 2
  Ny: 6
  n: 
  id:
  p: -1
  q: 3 

resarach_question: 'phase optimization with inital theta guess + SLSQP optimizer with interaction = 1'

config0:
  band_energy: 1
  interaction_strength: 1
  ground_state_degeneracy: 
  overlap_optimization: False
  maxiter: 1000000
  random_initial_parametrs: False
  loss: 
  # optimizer: 'my_optimizer'
  # optimizer: 'my_optimizer_V2'
  # optimizer: 'SPSA'
  optimizer: 'SLSQP'
  # optimizer: 'cobyla'
  # optimizer: 'BFGS'
  cktp_iters: 
