simulation_type: jax

data:
  name: RFCI
  Nx: 2
  Ny: 6
  n: 
  id:
  p: -1
  q: 3 

resarach_question: 'run (2,6) with overlap but energy opti'

config0:
  band_energy: 1
  interaction_strength: 2
  ground_state_degeneracy: 3
  overlap_optimization: False
  maxiter: 10000000
  layer_numer: 4
  random_initial_parametrs: False
  loss: 
  # optimizer: 'my_optimizer'
  # optimizer: 'my_optimizer_V2'
  # optimizer: 'SPSA'
  # optimizer: 'SLSQP'
  # optimizer: 'cobyla'
  optimizer: 'BFGS'
  cktp_iters: 200
