simulation_type: qiskit

data:
  name: RFCI
  Nx: 3
  Ny: 3
  extention_factor: 1
  n: 
  id: 

resarach_question: 'wandb test'

config1:
  band_energy: 1
  interaction_strength: 0.1
  translation_invariant_ansatz: True
  anzts_reps: 1
  flux_attch: True
  maxiter: 2
  NNN: False
  # loss: !lambda 'x:  -1/np.sqrt(2*np.pi*10) * np.exp(-(x + 2.999)**2 / (2*10**2)) * 100'
  loss: 
  cooling_protocol: False
