data:
  name: RFCI
  Nx: 6
  Ny: 2
  extention_factor: 1
  n: 
  id: ''

config1:
  band_energy: 1
  interaction_strength: 0.1
  translation_invariant_ansatz: True
  anzts_reps: 1
  flux_attch: False
  maxiter: 100
  NNN: False
  loss:
  cooling_protocol: False

config2:
  band_energy: 1
  interaction_strength: 0.1
  translation_invariant_ansatz: True
  anzts_reps: 1
  flux_attch: True
  maxiter: 100
  NNN: False
  loss:
  cooling_protocol: False



