data:
  name: RFCI
  Nx: 2
  Ny: 2
  extention_factor: 3
  n: 
  id: '4.1'

resarach_question: 'is 2 iteration enougth? and then flux attach 2 and then long optimization'

config1:
  band_energy: 1
  interaction_strength: 0
  translation_invariant_ansatz: False
  anzts_reps: 3
  flux_attch: False
  maxiter: 2
  NNN: True
  loss:
  cooling_protocol: False

config2:
  band_energy: 1
  interaction_strength: 0.1
  translation_invariant_ansatz: False
  anzts_reps: 3
  flux_attch: True
  maxiter: 2
  NNN: False
  loss:
  cooling_protocol: False

config3:
  band_energy: 1
  interaction_strength: 0.1
  translation_invariant_ansatz: False
  anzts_reps: 1
  flux_attch: False
  maxiter: 1000
  NNN: False
  loss:
  cooling_protocol: True


