data:
  name: RFCI
  Nx: 2
  Ny: 2
  extention_factor: 3
  n: 
  id: '1.1'

resarach_question: 'is 2 iteration enougth?'

config1:
  band_energy: 1
  interaction_strength: 0
  translation_invariant_ansatz: False
  anzts_reps: 3
  flux_attch: False
  maxiter: 2
  NNN: True
  loss:
  cooling_protocol: False

config2:
  band_energy: 1
  interaction_strength: 0.1
  translation_invariant_ansatz: False
  anzts_reps: 3
  flux_attch: True
  maxiter: 2
  NNN: False
  loss:
  cooling_protocol: False



