data:
  name: RFCI
  Nx: 2
  Ny: 2
  extention_factor: 3
  n: 
  id: '2'

resarach_question: 'given enougth iteration of spreading and then flux inserting will it convege with strong interaction at first?'

config1:
  band_energy: 1
  interaction_strength: 1000
  translation_invariant_ansatz: False
  anzts_reps: 3
  flux_attch: False
  maxiter: 500
  NNN: True
  loss:
  cooling_protocol: False

config2:
  band_energy: 1
  interaction_strength: 0.1
  translation_invariant_ansatz: False
  anzts_reps: 3
  flux_attch: True
  maxiter: 500
  NNN: False
  loss:
  cooling_protocol: False



