data:
  name: RFCI
  Nx: 1
  Ny: 3
  extention_factor: 3
  n: 
  id: 'test'

resarach_question: '?'

config1:
  band_energy: 1
  interaction_strength: 0
  translation_invariant_ansatz: False
  anzts_reps: 2
  flux_attch: False
  maxiter: 1000
  NNN: False
  loss: !lambda 'x:  x'
  cooling_protocol: False



