data:
  name: RFCI
  Nx: 1
  Ny: 3
  extention_factor: 3
  n: 
  id: 'loss_test_3'

resarach_question: 'checking convergences with loss ansatz'

config1:
  band_energy: 1
  interaction_strength: 0
  translation_invariant_ansatz: False
  anzts_reps: 3
  flux_attch: False
  maxiter: 1000
  NNN: False
  loss: !lambda 'x:  -(np.exp(-(x+3.1)**2 * 5)) * 100'
  cooling_protocol: False



